# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{radish}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Glenn Vanderburg"]
  s.date = %q{2010-03-11}
  s.description = %q{A library for building parsers using top-down operator precedence}
  s.email = %q{glv@vanderburg.org}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "Gemfile",
     "Gemfile.lock",
     "LICENSE",
     "README.md",
     "Rakefile",
     "VERSION",
     "features/calculator.feature",
     "features/javascript_lexer.feature",
     "features/javascript_parser.feature",
     "features/step_definitions/calculator_steps.rb",
     "features/step_definitions/javascript_parser_steps.rb",
     "features/support/env.rb",
     "lib/radish.rb",
     "lib/radish/errors.rb",
     "lib/radish/lexer.rb",
     "lib/radish/lexer_token.rb",
     "lib/radish/parser.rb",
     "lib/radish/scoping.rb",
     "lib/radish/token.rb",
     "samples/calculator.rb",
     "samples/simplified_javascript/javascript_lexer.rb",
     "samples/simplified_javascript/javascript_parser.rb",
     "spec/radish/errors_spec.rb",
     "spec/radish/lexer_spec.rb",
     "spec/radish/parser_spec.rb",
     "spec/radish/scoping_spec.rb",
     "spec/radish/token_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/be_token.rb",
     "specs.watchr",
     "test.rb",
     "vendor/cache/activesupport-3.0.0.beta.gem",
     "vendor/cache/builder-2.1.2.gem",
     "vendor/cache/cucumber-0.6.3.gem",
     "vendor/cache/diff-lcs-1.1.2.gem",
     "vendor/cache/gemcutter-0.5.0.gem",
     "vendor/cache/git-1.2.5.gem",
     "vendor/cache/i18n-0.3.5.gem",
     "vendor/cache/jeweler-1.4.0.gem",
     "vendor/cache/json_pure-1.2.2.gem",
     "vendor/cache/memcache-client-1.7.8.gem",
     "vendor/cache/polyglot-0.3.0.gem",
     "vendor/cache/rake-0.8.7.gem",
     "vendor/cache/rcov-0.9.8.gem",
     "vendor/cache/rr-0.10.10.gem",
     "vendor/cache/rspec-2.0.0.beta.2.gem",
     "vendor/cache/rspec-core-2.0.0.beta.2.gem",
     "vendor/cache/rspec-expectations-2.0.0.beta.2.gem",
     "vendor/cache/rspec-mocks-2.0.0.beta.2.gem",
     "vendor/cache/rubyforge-2.0.4.gem",
     "vendor/cache/term-ansicolor-1.0.4.gem",
     "vendor/cache/treetop-1.4.4.gem",
     "vendor/cache/tzinfo-0.3.16.gem"
  ]
  s.homepage = %q{http://github.com/glv/radish}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A library for building parsers using top-down operator precedence}
  s.test_files = [
    "spec/radish/errors_spec.rb",
     "spec/radish/lexer_spec.rb",
     "spec/radish/parser_spec.rb",
     "spec/radish/scoping_spec.rb",
     "spec/radish/token_spec.rb",
     "spec/spec_helper.rb",
     "spec/support/be_token.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0.beta"])
      s.add_development_dependency(%q<cucumber>, [">= 0.6.3"])
      s.add_development_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_development_dependency(%q<rr>, [">= 0.10.10"])
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.a7"])
      s.add_development_dependency(%q<rcov>, [">= 0.9.8"])
    else
      s.add_dependency(%q<activesupport>, [">= 3.0.0.beta"])
      s.add_dependency(%q<cucumber>, [">= 0.6.3"])
      s.add_dependency(%q<jeweler>, [">= 1.4.0"])
      s.add_dependency(%q<rr>, [">= 0.10.10"])
      s.add_dependency(%q<rspec>, [">= 2.0.0.a7"])
      s.add_dependency(%q<rcov>, [">= 0.9.8"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 3.0.0.beta"])
    s.add_dependency(%q<cucumber>, [">= 0.6.3"])
    s.add_dependency(%q<jeweler>, [">= 1.4.0"])
    s.add_dependency(%q<rr>, [">= 0.10.10"])
    s.add_dependency(%q<rspec>, [">= 2.0.0.a7"])
    s.add_dependency(%q<rcov>, [">= 0.9.8"])
  end
end

